### PR TITLE
Try to fix the spacing consistency

### PR DESCRIPTION
**Pull request by mitchellkrome**
I made a branch this time hopefully third time lucky and I don't end up with more commits in here...

### CODE REVIEW

**Comment by joelfenwick** [comment]
Everything except arraysandpointers.tex is fine.
Is there a reason for getting rid of the mention of pointers from those lines?

**Comment by mitchellkrome** [comment]
I think that was because the lines went way off the side of the margin and it looked bad. Maybe the old comment above would be better?

**Comment by joelfenwick** [comment]
Ok, make the old comment fit and recommit and I'll merge it.

**Comment by mitchellkrome** [comment]
Okay done

**Pull request merged**
